base:
  mass: 1.0               # Base mass in Kg
  x_size: 0.245           # Dimension in x axis
  y_size: 0.162            # Dimension in y axis
  z_size: 0.02          # Dimension in z axis
  mesh: 'chassis.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  #mesh: ''