mass: 0.5        # Wheel mass in Kg
radius: 0.05125    # Wheel radius in m
length: 0.0428     # Wheel length in m, considering is as a cylinder
mesh: '../components/wheel.stl'          # Name of the mesh files. Leave it empty ('') to have a red wheel
#mesh: ''
scale: ''
x_offset: 0
y_offset: 0.05575
z_offset: 0
